### ISSUE TITLE
Compiler error for Arduino 1.8.5

### ISSUE THREAD

**Issue by haarislabs** [mrt-prodz/ATmega328-Tiny-3D-Engine#1]
Hi,

I have ardiuno uno board interfaced with TFT screen st7735 and when I use your code it shows me an error in compiling .

`C:\Users\Haaris Moosa\Desktop\arduino-1.8.5\hardware\tools\avr/bin/avr-gcc" -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega328p -w -flto -fuse-linker-plugin -o 
 tiny_3d_engine:157: error: unable to find a register to spill in class 'POINTER_REGS'`

I have only listed the errors which are useful

I googled it and it's a gcc compiler error. I'm using gcc 4.9.2
Can you please share your gcc version and the Arduino IDE version that you were using?

**Comment by mrt-prodz** [comment]
Hello @haarislabs ,

I had a look into my old Windows partition and I was using Arduino IDE 1.6.4 with avr-gcc 4.8.1, however I also compiled the project without issue using the latest Arduino IDE 1.8.5 that I am currently running. (I just tested to build the project right now, avr-gcc 7.2.0 on Fedora)

Looking at the error it seems the compiler is not appreciating ```Matrix4 mMultiply``` , could you try another version of avr-gcc as it seems 4.9.2 had some issue after Googling this error ? Is it possible for you to upgrade ?

**Comment by per1234** [comment]
There's a workaround described here:
https://github.com/arduino/Arduino/issues/3972#issuecomment-147707385

**Comment by haarislabs** [comment]
Hey @mrt-prodz ,
I used arduino 1.6.4 and it complies without any error. Thanks :) . Do you know how can I upgrade my gcc ? I'm using windows 8.
@per1234 I couldn't quite figure that, to just optimize on function they used  :
`float getSlope(float history[]) __attribute__((__optimize__("O2")));`

In my case I have a structure fucntion that needs optimization as far as I know :

I added those optimization line but it shows the same error
`Matrix4 mMultiply(const Matrix4 &mat1, const Matrix4 &mat2) __attribute__((__optimize__("O2")));
Matrix4 mMultiply(const Matrix4 &mat1, const Matrix4 &mat2)  {
  Matrix4 mat;
  unsigned char r,c;
  for (c=0; c<4; c++)
    for (r=0; r<4; r++)
      mat.m[c][r] = pMultiply(mat1.m[0][r], mat2.m[c][0]) +
                    pMultiply(mat1.m[1][r], mat2.m[c][1]) +
                    pMultiply(mat1.m[2][r], mat2.m[c][2]) +
                    pMultiply(mat1.m[3][r], mat2.m[c][3]);
  return mat;
}`

**Comment by mrt-prodz** [comment]
@haarislabs you might want to try following these instructions: http://blog.zakkemble.co.uk/avr-gcc-builds/

I didn't try anything like this so you might want to stay careful if you use multiple libraries regarding compatibility issues.

**Comment by haarislabs** [comment]
@mrt-prodz I think you are correct, I should look for workarounds for this issue. So far I have tried the above method mentioned by @per1234  and [https://github.com/arduino/Arduino/issues/2413](url) , but none of them are working for me

**Comment by mrt-prodz** [comment]
@haarislabs : If you don't mind, since this was more a compiler issue rather than something regarding the code of this repository I'm closing this.
