### ISSUE TITLE
python 3 is not supported by stl2h, so here is the conversation for python3

### ISSUE THREAD

**Issue by jamesdanielv** [mrt-prodz/ATmega328-Tiny-3D-Engine#4]
//python 3 is not supported by stl2h.py , so here is the conversation for python3..
//online formatting of text might be incorrect so copy and put into a file.. i'm hesitant to change original file at this point 
//and leave it up to original authors..
//modified by james villeneuve in 2022 for stl to file conversion for  arduino stl files for tiny 3d engine
//using https://www.tutorialspoint.com/online_python_formatter.htm to clean up tab issues
//and using a python 2to3 converter online tool https://python2to3.com/#!/usr/bin/python
//just save in any working directory as stl2h.py 
// to use you will most likely need to decimate stl file to under 700 faces in blender and then
//use a program like meshlab to convert it from binary stl to text based output.
//below is an example that uses a file called my_stl_file.stl output file text.txt and scales item by 5.
//example use is python3 stl2h.py -i my_stl_file.stl -o text.txt -s 5

file for python3 is here. https://github.com/jamesdanielv/pyhton3convertof-stl2h.py

**Comment by jamesdanielv** [comment]
i moved the file to a separate location as the github comments removed the tabs. i will also make my own fork of the tiny3d. i just thought an answer should be brought forward to the original script to update it to python3. there were some tab violations in original code that made 2to3 script not work, and was addressed thru auto clean formatter tool, then online conversion. i didn't see an update to code online. ok best!

**Comment by mrt-prodz** [comment]
Greetings @jamesdanielv , feel free to fork the project and add your Python 3 version of stl2h.py, I will gladly accept a merge request. Thank you very much !

**Comment by jamesdanielv** [comment]
i submitted a pull request to merge it. hopefully everything goes smoothly.

**Comment by mrt-prodz** [comment]
Thank you once again @jamesdanielv , as mentioned in #5 I patched the old converter into a new file `stl2h-py3.py`
